# Generated by Django 5.1.7 on 2025-04-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_patient_allergies_patient_blood_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
