# Generated by Django 5.1.7 on 2025-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_consultation_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthjournalentry',
            name='doctor_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthjournalentry',
            name='pain_severity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthjournalentry',
            name='symptom_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthjournalentry',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
