# Generated by Django 5.1.7 on 2025-04-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_healthjournalentry_doctor_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthjournalentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='healthjournalentry',
            name='mood',
        ),
        migrations.RemoveField(
            model_name='healthjournalentry',
            name='symptom_type',
        ),
        migrations.AddField(
            model_name='healthjournalentry',
            name='symptom',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
