# Generated by Django 5.1.7 on 2025-04-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_healthjournalentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='healthjournalentry',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
