# Generated by Django 5.1.7 on 2025-04-13 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_consultation_condition_healthjournalentry_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='condition',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthjournalentry',
            name='condition',
            field=models.CharField(default='Not Specified', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VirtualVisit',
        ),
    ]
